### ISSUE TITLE
Выдаёт ошибку 

### ISSUE THREAD

**Issue by Letomaniy** [alirzaev/static-qt-build-manual#1]
Привет, помоги пожалуйста. Не могу понять из-за чего это может быть(думал из-за отсутствия Python но нет, скачал и пишет тоже самое) 
![image](https://user-images.githubusercontent.com/61186211/76617979-7ee91580-6538-11ea-9657-f3b6b9d10749.png)
![image](https://user-images.githubusercontent.com/61186211/76618035-9e803e00-6538-11ea-8f14-1aeba376ffca.png)

**Comment by alirzaev** [comment]
Судя по всему `python.exe` не найден, потому что папка с этим файлом не добавлена в переменную `PATH`

Добавить ее можно, например, таким образом (действует только для текущей сессии консоли):

```
set PATH=C:\Program Files\Python37;%PATH%
```

Вместо `C:\Program Files\Python37` возможно нужно будет подставить другой путь
